[#182] Add support for GenQuery2 to genquery.py module (4-3-stable)
irods/irods_rule_engine_plugin_python pull request #206
Opened 2024-06-11 16:29 UTC by korydraughn

The current implementation works, but it's still a WIP.

2024-06-11 16:40 UTC, trel commented on genquery.py
> +    :param parser_impl:    (optional) use GenQuery1 or GenQuery2 as the query engine
declare the default

2024-06-11 16:41 UTC, trel commented on genquery.py
> +    :param parser_impl:    (optional) use GenQuery1 or GenQuery2 as the query engine
and are these capitalized?  does it matter?   later, the error message says 'Expected GENQUERY1 or GENQUERY2'.

2024-06-11 16:43 UTC, korydraughn commented on genquery.py
> +                return
Add comment explaining why we return early.

2024-06-11 16:43 UTC, korydraughn commented on genquery.py
> +            return
Does this have any issues? Hmm ...

2024-06-11 16:43 UTC, korydraughn commented on genquery.py
> +                 parser_impl=Parser_Impl.GENQUERY1):
Needs a test.

2024-06-11 16:43 UTC, korydraughn commented on genquery.py
> +def row_generator(columns, conditions, row_return, callback, parser_impl=Parser_Impl.GENQUERY1):
Needs a test.

2024-06-11 16:43 UTC, korydraughn commented on genquery.py
> +            if self.parser_impl == Parser_Impl.GENQUERY1:
Add comment explaining why this operation results in a no-op when using GenQuery2.

2024-06-11 16:45 UTC, trel commented
also consider the upcoming work with 'zone_hint'... in case the positional arguments in this PR should wait for that one first... not sure, discush!

2024-06-11 16:47 UTC, korydraughn commented on genquery.py
> +    :param parser_impl:    (optional) use GenQuery1 or GenQuery2 as the query engine
> and are these capitalized? does it matter? 

That line is only a placeholder at the moment. The plan is to circle back and clean everything up once the implementation is good.

2024-06-11 16:51 UTC, korydraughn commented
I'll handle the zone hint after this PR is complete and merged. The zone hint will be an optional parameter, so there's nothing to worry about in regard to merge order.

2024-06-11 16:54 UTC, trel commented
just thinking it might be better to have zone hint before genquery parser option.   you're right, doesn't really matter in the long run.

2024-06-25 20:53 UTC, korydraughn commented
@lwesterhof Do you rely on the `total_rows` member function?

GenQuery2 may not be able to support all functionality of the GenQuery python module due to GenQuery2 being very different from GenQuery1.

Thoughts?

2024-06-26 01:48 UTC, korydraughn commented
I see two ways to support a zone hint.
- (A) Modify the existing GenQuery1 MSIs to parse the zone hint from an existing input argument
    - We cannot add additional input parameters, hence the need for a little string-based parsing
- (B) Or, add a new MSI for GenQuery1 which allows the zone hint to be set

Notice, I'm talking about the MSIs and not the python module being modified in this PR.

2024-06-26 08:08 UTC, lwesterhof commented
> @lwesterhof Do you rely on the `total_rows` member function?
> 
> GenQuery2 may not be able to support all functionality of the GenQuery python module due to GenQuery2 being very different from GenQuery1.
> 
> Thoughts?

We do rely on it in a couple of instances. But I think we can easily work around those cases.

2024-06-28 02:47 UTC, korydraughn commented on genquery.py
> +    :param parser_impl:    (optional) use GenQuery1 or GenQuery2 as the query engine
Updated.

2024-06-28 02:48 UTC, korydraughn commented on genquery.py
> +            return
Updated.

2024-06-28 02:48 UTC, korydraughn commented on genquery.py
> +            if self.parser_impl == Parser_Impl.GENQUERY1:
Done.

2024-06-28 02:49 UTC, korydraughn commented on genquery.py
> +                return
Done.

2024-06-28 02:54 UTC, korydraughn commented
@lwesterhof Consider giving the current implementation a try in your test environment. Copying the file is all that's necessary. That would help a lot in figuring out what's missing.

2024-07-08 18:30 UTC, alanking reviewed
Given the limitations of this interface, are there any plans to make a genquery2 iterator module that enables the GenQuery2-only features?

2024-07-08 18:30 UTC, alanking commented on genquery.py
> +      This only applies when GenQuery1 is used.
What only applies when GenQuery1 is used? The different `output` options?

2024-07-08 18:33 UTC, korydraughn commented
> Given the limitations of this interface, are there any plans to make a genquery2 iterator module that enables the GenQuery2-only features?

There aren't any plans at the moment. Not against it. Feel free to take a swing at designing the interface (no implementation yet) if you like. Happy to discuss more.

2024-07-08 18:36 UTC, korydraughn commented on genquery.py
> +      This only applies when GenQuery1 is used.
Correct. I'm considering rewriting the docstrings so it's easier to understand what's for what.

Of course that won't be part of this PR, so here we are :)

Suggestions welcome.

2024-07-08 22:13 UTC, alanking commented on genquery.py
> +      This only applies when GenQuery1 is used.
Oh, okay. Sounds good. I have no further suggestions at this time.

2024-07-09 11:31 UTC, d-w-moore requested changes

2024-07-09 11:31 UTC, d-w-moore commented on genquery.py
> +_END_OF_RESULTSET_ERROR_STRING_PART = f':{str(END_OF_RESULTSET)}]'
I  think this is equivalent to : 
```
_END_OF_RESULTSET_ERROR_STRING_PART = str(END_OF_RESULTSET) + "]"
```
Is that correct?
I'm not sure which is clearer.

2024-07-09 11:31 UTC, d-w-moore commented on genquery.py
> +from irods_errors import END_OF_RESULTSET
How / where does the symbol `END_OF_RESULTSET `get defined?  I can't tell by perusing the source of `src/irods_errors.cpp`

2024-07-09 11:36 UTC, d-w-moore commented on genquery.py
> +_END_OF_RESULTSET_ERROR_STRING_PART = f':{str(END_OF_RESULTSET)}]'
Actuallly this might work just as well:
```
f':{END_OF_RESULTSET}]'
```
Because `str` is implied.

2024-07-09 11:47 UTC, d-w-moore commented on genquery.py
> +_END_OF_RESULTSET_ERROR_STRING_PART = f':{str(END_OF_RESULTSET)}]'
If str can be omitted, I'd call it a wash either way, whether you want to use the + form or f'' form.  You can interpret the first part of this comment as I was just getting confused looking at all the different parens, so feel free to ignore....

2024-07-09 12:36 UTC, korydraughn commented on genquery.py
> +_END_OF_RESULTSET_ERROR_STRING_PART = f':{str(END_OF_RESULTSET)}]'
There's a semicolon at the front which is why I chose an f-string.

2024-07-09 12:37 UTC, korydraughn commented on genquery.py
> +from irods_errors import END_OF_RESULTSET
I'm pretty sure it's derived from rodsErrorTable.h in irods/irods.

2024-07-09 12:40 UTC, korydraughn commented on genquery.py
> +_END_OF_RESULTSET_ERROR_STRING_PART = f':{str(END_OF_RESULTSET)}]'
Ignore my last comment - I didn't see the others.

I'll give `f':{END_OF_RESULTSET}]'` a try.

2024-07-09 17:28 UTC, korydraughn commented on genquery.py
> +_END_OF_RESULTSET_ERROR_STRING_PART = f':{str(END_OF_RESULTSET)}]'
That appears to work at the bench.

Will test it via the testing environment to be sure.

2024-07-12 07:13 UTC, lwesterhof commented
> @lwesterhof Consider giving the current implementation a try in your test environment. Copying the file is all that's necessary. Your feedback would help a lot in figuring out what's missing.

We're on iRODS 4.2.12, so our test environments are stuck with Python 2 for now. We're planning to start the upgrade to iRODS 4.3.x soon. We'll definitely share our feedback once we get to test it.

2024-07-12 13:10 UTC, korydraughn commented
Good to know. This is very close to completion so we'll move forward with testing and getting this merged.

We can always tweak and release a new version.

2024-07-17 18:43 UTC, korydraughn commented on genquery.py
> +                 parser_impl=Parser_Impl.GENQUERY1):
Reverted. No test needed.

2024-07-17 18:43 UTC, korydraughn commented on genquery.py
> +def row_generator(columns, conditions, row_return, callback, parser_impl=Parser_Impl.GENQUERY1):
Reverted. No test needed.

2024-07-17 18:58 UTC, korydraughn commented on genquery.py
> +                    self._close()
Add `return` after `_close()`.

2024-07-17 18:58 UTC, korydraughn commented on genquery.py
> +    return (row for row in row_iterator(columns, conditions, row_return, callback, parser=Parser.GENQUERY1))
This isn't necessary because `row_iterator` doesn't expose `parser`.

2024-07-17 18:58 UTC, korydraughn commented on genquery.py
> +        self.generator = row_generator (columns, conditions, row_return, callback, parser=Parser.GENQUERY1)
`row_generator` doesn't expose `parser`.

2024-07-17 18:58 UTC, korydraughn commented on genquery.py
> +    return Query(callback, columns, conditions, output=row_return, parser=Parser.GENQUERY1)
Revert. `Query` defaults to GenQuery1.

2024-07-17 20:47 UTC, korydraughn commented on genquery.py
> +                    self._close()
Done.

2024-07-17 20:47 UTC, korydraughn commented on genquery.py
> +    return (row for row in row_iterator(columns, conditions, row_return, callback, parser=Parser.GENQUERY1))
Reverted.

2024-07-17 20:47 UTC, korydraughn commented on genquery.py
> +        self.generator = row_generator (columns, conditions, row_return, callback, parser=Parser.GENQUERY1)
Done.

2024-07-17 20:47 UTC, korydraughn commented on genquery.py
> +    return Query(callback, columns, conditions, output=row_return, parser=Parser.GENQUERY1)
Done.

2024-07-17 22:18 UTC, korydraughn commented on genquery.py
> +_END_OF_RESULTSET_ERROR_STRING_PART = f':{str(END_OF_RESULTSET)}]'
The suggested change works as intended.

2024-07-17 23:01 UTC, korydraughn commented
TODO: Add documentation to README.

2024-07-18 12:21 UTC, korydraughn commented on genquery.py
> +    """Incompatible with GenQuery2 parser."""
done

2024-07-18 12:21 UTC, korydraughn commented on genquery.py
> +    """Incompatible with GenQuery2 parser."""
done

2024-07-18 12:21 UTC, korydraughn commented on genquery.py
> +    """Incompatible with GenQuery2 parser."""
done

2024-07-18 12:37 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
The last statement is in conflict with the `__iter__` function.

The query object will close the resultset after a complete iteration of the data. That allows the query object to be re-executed and iterated over again. However, the rows returned may be different due to the querying of the catalog.

I'm considering the idea of adding a `close` member function so users can decide when the cached resultset isn't needed any longer. This also gives the users control over when the query object should reach out to the catalog.

2024-07-18 12:38 UTC, korydraughn commented on genquery.py
> +                        self._close()
This is what I'm referring to in https://github.com/irods/irods_rule_engine_plugin_python/pull/206/files#r1682764576.

2024-07-18 12:39 UTC, korydraughn commented
This is now ready for final review.

2024-07-18 17:35 UTC, alanking reviewed
Seems good. Maybe another look from @d-w-moore would be beneficial here

2024-07-18 19:21 UTC, trel commented on README.md
> +As of iRODS 4.3.3, the following parameters are optional:
> Or, just get rid of this mention of the version entirely and include this parameter in the above list of optional parameters.

just including in the list as optional above seems sufficient... (perhaps with a 'since 4.3.3.0' note?)

2024-07-18 20:04 UTC, korydraughn commented on README.md
> +As of iRODS 4.3.3, the following parameters are optional:
Will update

2024-07-18 20:08 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
Please elaborate on what pushes you in the direction of waiting on the proposed change?

2024-07-19 14:49 UTC, alanking commented on genquery.py
> +            # executed again, a new Query object must be used.
If it impacts the existing behavior of the genquery iterator, it would make me uneasy to introduce such a change so close to release, and a "minor" one at that. If it is just an additional knob that does not impact existing behavior, then it's fine.

2024-07-19 15:48 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
After some discussion, we've decided that exposing `close()` is pointless because the GenQuery2 MSIs do not expose a way to do random access on a resultset. This decision aligns with the original design of the `Query` class too _(i.e. instantiate a new instance of `Query` if fresh results are needed)_.

2024-07-19 17:24 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
After reviewing the code a bit more, users have always had the ability to manually close the resultset via the `del` instruction. For example:
```python
my_query = Query(...)
del my_query # Just calls self._close()
```

Being able to manually close the resultset is important for GenQuery2 because it releases the memory attached to the handle.

Now, do we like/want users to use `del` to cleanup resources or would a `close()` function be better?

2024-07-19 17:41 UTC, korydraughn commented on README.md
> +As of iRODS 4.3.3, the following parameters are optional:
Done

2024-07-19 17:43 UTC, alanking commented on genquery.py
> +            # executed again, a new Query object must be used.
I defer to @d-w-moore for opinions on what a pythonic mind might expect.

2024-07-19 17:43 UTC, korydraughn commented on genquery.py
> +                        self._close()
Done

2024-07-22 17:15 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
@d-w-moore Any thoughts on https://github.com/irods/irods_rule_engine_plugin_python/pull/206/files#r1684688435?

2024-07-22 17:24 UTC, korydraughn commented
The interface of the `Query` class likely needs to expose an option for sorting results when using GenQuery2. Providing that allows the `Query` class to cover more cases.

2024-07-22 18:49 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
After some discussion with @d-w-moore, I've now learned that `del` is not equivalent to providing a dedicated close member function. That instruction is all about the reference count and garbage collection.

The correct approach is to provide a public close member function. That ultimately means renaming `_close()` to `close()`.

Will open an issue for renaming the function and get that implemented.

2024-07-22 19:46 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
Created #213.

2024-07-22 19:47 UTC, korydraughn commented
Added support for order-by. Just need to add tests.

2024-07-22 20:13 UTC, alanking reviewed
New changes seem good.

I didn't realize that the in-line conditional for the `order_by_clause` operated that way. I thought that this...
```python
>>> s = 'hello' + ' world' if False else ''
>>> s
''
```
...was going to do this:
```python
>>> s = 'hello' + ' world' if False else ''
>>> s
'hello'
```
Good to know.

2024-07-22 20:13 UTC, alanking commented on README.md
> +As a best practice, when using GenQuery2, prefer calling the `close()` member function when done processing the resultset. Doing this will instruct the server to immediately free any resources alloca
I find the "prefer" and "extremely important" juxtaposition a little awkward here. How does this wording look?
```suggestion
When a GenQuery2 resultset is done being processed, it is best practice to call the `close()` member function. Doing this will instruct the server to immediately free any resources allocated to the `Query` object. This is extremely important when multiple `Query` objects are executed within a single rule.
```

2024-07-22 20:13 UTC, alanking commented on genquery.py
> +    :param order_by:       (optional) order-by clause, as a string. defaults to an empty string. applies when using the GenQuery2 parser
Perhaps "only recognized by the GenQuery2 parser" is a bit clearer?

Also, maybe we don't need to document this here because it's not the right place, but what kinds of values do we pass in "as a string" here? Column names, right?

2024-07-22 20:57 UTC, korydraughn commented
> New changes seem good.
> 
> I didn't realize that the in-line conditional for the `order_by_clause` operated that way. I thought that this...
> 
> ```python
> >>> s = 'hello' + ' world' if False else ''
> >>> s
> ''
> ```
> 
> ...was going to do this:
> 
> ```python
> >>> s = 'hello' + ' world' if False else ''
> >>> s
> 'hello'
> ```
> 
> Good to know.

I actually didn't even think about that lol. I copied some existing lines and changed them to fit my needs. I guess I just got lucky.

2024-07-22 21:01 UTC, korydraughn commented on genquery.py
> +    :param order_by:       (optional) order-by clause, as a string. defaults to an empty string. applies when using the GenQuery2 parser
> Perhaps "only recognized by the GenQuery2 parser" is a bit clearer?

Will update.

> Also, maybe we don't need to document this here because it's not the right place, but what kinds of values do we pass in "as a string" here? Column names, right?

Correct. Will update the README info that.

I'm planning on adding a few examples to the README demonstrating how to use GenQuery2 via this interface.

2024-07-22 21:02 UTC, korydraughn commented on genquery.py
> +            # executed again, a new Query object must be used.
Done.

2024-07-22 21:27 UTC, korydraughn commented on README.md
> +As a best practice, when using GenQuery2, prefer calling the `close()` member function when done processing the resultset. Doing this will instruct the server to immediately free any resources alloca
Done

2024-07-22 21:27 UTC, korydraughn commented
TODO: Add GenQuery2 examples to README.

2024-07-22 21:31 UTC, korydraughn commented on genquery.py
> +    :param order_by:       (optional) order-by clause, as a string. defaults to an empty string. applies when using the GenQuery2 parser
Updated documentation for order_by.

Captured the GenQuery2 examples effort in a separate comment. See  https://github.com/irods/irods_rule_engine_plugin_python/pull/206#issuecomment-2243844827

2024-07-22 21:59 UTC, korydraughn commented
The only thing that remains now is writing up `Query` examples using GenQuery2.

2024-07-23 16:04 UTC, alanking reviewed
Yep, new changes seem good. I have nothing to add. Should we squash? Get a second opinion?

2024-07-23 16:08 UTC, korydraughn commented
I was thinking about rewording the additions to the Q&A section. If I decide to leave it as is, I'll go ahead and squash the commits.

2024-07-24 00:07 UTC, trel commented on README.md
> +```python
show the string that is being embedded... I think it is `'_quotes_around_me_'`

2024-07-24 00:07 UTC, trel commented on README.md
> +- Use a single quote to escape a single quote as defined by the SQL standard
can we see an example of this first format as well?

2024-07-24 00:07 UTC, trel commented on README.md
> +Assume we have five collections and we want to sort them by the length of their logical path, but in descending order.
perhaps a third example with data object size?  Does it know it's a number?  Does it sort 12, 5, and 321 correctly?

2024-07-24 00:07 UTC, trel commented on genquery.py
> +    :param order_by:       (optional) order-by clause, as a string. defaults to an empty string. only recognized by the GenQuery2 parser
capital letters at beginning of sentences?... not sure what you've done in other places like this.

2024-07-24 00:23 UTC, korydraughn commented on README.md
> +  * *order_by* is a string holding the sorting instructions for a GenQuery2 query. Defaults to an empty string. Only recognized by the GenQuery2 parser.
Which options are you referring to?

`order_by` accepts any string as long as it follows the SQL rules for the ORDER-BY clause.

2024-07-24 00:29 UTC, korydraughn commented on README.md
> +When a GenQuery2 resultset is done being processed, it is best practice to call the `close()` member function. Doing this will instruct the server to immediately free any resources allocated to the `
The use of word, `processing`, is little weird to me.

What are your thoughts on the following?
```
When a GenQuery2 resultset is no longer needed, ...
```
Or
```
When processing of a GenQuery2 resultset is complete, ...
```

2024-07-24 00:30 UTC, korydraughn commented on README.md
> +```python
Will do.

2024-07-24 00:34 UTC, trel commented on README.md
> +  * *order_by* is a string holding the sorting instructions for a GenQuery2 query. Defaults to an empty string. Only recognized by the GenQuery2 parser.
if that is 'known' then it doesn't need to go here...   but... maybe a mention of 'standard SQL' or something.

2024-07-24 00:35 UTC, trel commented on README.md
> +When a GenQuery2 resultset is done being processed, it is best practice to call the `close()` member function. Doing this will instruct the server to immediately free any resources allocated to the `
ah,, yes....    

`When the processing of a GenQuery2 resultset is complete ...`

2024-07-24 00:48 UTC, korydraughn commented on README.md
> +Assume we have five collections and we want to sort them by the length of their logical path, but in descending order.
Sorting is handled by the database. My guess is the results can vary depending on the configuration of the database _(i.e. organizations can use different collations)_.

Here's what I get with `iquery`.
```bash
$ ils -l
/tempZone/home/kory:
  kory              0 demoResc            0 2024-07-22.14:01 & 0.txt
  kory              0 demoResc          321 2024-07-23.20:35 & 321.bin
  kory              0 demoResc            6 2024-07-23.20:33 & bar
  kory              0 demoResc           29 2024-07-23.20:34 & cats
  kory              0 demoResc            0 2024-07-17.16:53 & foo
  kory              0 demoResc            0 2024-07-19.21:11 & thinger
$ iquery "select DATA_SIZE order by DATA_SIZE" | jq
[
  [
    "0"
  ],
  [
    "6"
  ],
  [
    "29"
  ],
  [
    "321"
  ]
]
$ iquery "select DATA_SIZE order by DATA_SIZE desc" | jq
[
  [
    "321"
  ],
  [
    "29"
  ],
  [
    "6"
  ],
  [
    "0"
  ]
]
```
`iquery` appears to handle `DATA_SIZE` just fine.

Curious ... what does an example using `DATA_SIZE` offer over the current examples?

2024-07-24 00:51 UTC, korydraughn commented on genquery.py
> +    :param order_by:       (optional) order-by clause, as a string. defaults to an empty string. only recognized by the GenQuery2 parser
You're referring to the sentences following the period, correct?

2024-07-24 00:57 UTC, trel commented on README.md
> +Assume we have five collections and we want to sort them by the length of their logical path, but in descending order.
oh good - it knows they are ... integers/numbers somehow.

some people don't realize they can get more than just COLL_NAME, DATA_NAME - no real requirement to use DATA_SIZE.

2024-07-24 00:58 UTC, trel commented on genquery.py
> +    :param order_by:       (optional) order-by clause, as a string. defaults to an empty string. only recognized by the GenQuery2 parser
yes - and so capitalizing them makes them different from the first part of the lines... and not capitalizing them seems less formal and grown up.   hmm....

2024-07-24 01:00 UTC, korydraughn commented on README.md
> +  * *order_by* is a string holding the sorting instructions for a GenQuery2 query. Defaults to an empty string. Only recognized by the GenQuery2 parser.
Sure. Will adjust.

2024-07-24 01:19 UTC, korydraughn commented on README.md
> +Assume we have five collections and we want to sort them by the length of their logical path, but in descending order.
GenQuery2 also supports casting.

We have an open issue for documenting all of this in irods/irods_docs. I just haven't started writing it yet.

2024-07-24 01:26 UTC, trel commented on README.md
> +Assume we have five collections and we want to sort them by the length of their logical path, but in descending order.
yep, no worries - resolving.

2024-07-24 01:32 UTC, korydraughn commented on README.md
> +  * *order_by* is a string holding the sorting instructions for a GenQuery2 query. Defaults to an empty string. Only recognized by the GenQuery2 parser.
Done.

2024-07-24 01:32 UTC, korydraughn commented on README.md
> +When a GenQuery2 resultset is done being processed, it is best practice to call the `close()` member function. Doing this will instruct the server to immediately free any resources allocated to the `
Done.

2024-07-24 01:32 UTC, korydraughn commented on README.md
> +- Use a single quote to escape a single quote as defined by the SQL standard
Done.

2024-07-24 01:32 UTC, korydraughn commented on genquery.py
> +    :param order_by:       (optional) order-by clause, as a string. defaults to an empty string. only recognized by the GenQuery2 parser
Done.

2024-07-24 01:32 UTC, korydraughn commented on README.md
> +```python
Done.

2024-07-24 01:35 UTC, trel commented
looking good

2024-07-24 01:39 UTC, korydraughn commented
Will squash tomorrow morning unless there are additional review comments.

2024-07-24 13:37 UTC, korydraughn commented
Squashed. Will pound just before standup unless there are additional review comments.

2024-07-24 14:19 UTC, alanking approved these changes
I say # it

2024-07-24 15:18 UTC, korydraughn commented
#'d

2024-07-24 15:32 UTC, merged